## Preprocessing

In [21]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [22]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
#  YOUR CODE GOES HERE
application_df = application_df.drop(["EIN"], 1)
application_df.head()

<ipython-input-22-257636d022e3>:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  application_df = application_df.drop(["EIN"], 1)

,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [23]:
name_counts = application_df["NAME"].value_counts()
name_counts[name_counts > 5]

PARENT BOOSTER USA INC                             1260
TOPS CLUB INC                                       765
UNITED STATES BOWLING CONGRESS INC                  700
WASHINGTON STATE UNIVERSITY                         492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC     408
                                                   ...
OLD OAK CLIFF CONSERVATION LEAGUE INC                 6
AMERICAN NEPHROLOGY NURSES ASSOCIATION                6
HUMBLE ISD EDUCATIONAL SUPPORT GROUPS INC             6
PROFESSIONAL LOADMASTER ASSOCIATION                   6
CBMC INC                                              6
Name: NAME, Length: 354, dtype: int64

In [26]:
names_to_replace = list(name_counts[name_counts <= 5].index)
for app in names_to_replace:
  application_df["NAME"] = application_df["NAME"].replace(app, "Other")
  application_df["NAME"].value_counts()

In [27]:
# Determine the number of unique values in each column.
#  YOUR CODE GOES HERE
application_df.nunique()

NAME                       355
APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [29]:
# Look at APPLICATION_TYPE value counts for binning
#  YOUR CODE GOES HERE
application_counts = application_df["APPLICATION_TYPE"].value_counts()
application_counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [30]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
#  YOUR CODE GOES HERE
application_types_to_replace = list(application_counts[application_counts < 500].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [31]:
# Look at CLASSIFICATION value counts for binning
#  YOUR CODE GOES HERE
class_counts = application_df["CLASSIFICATION"].value_counts()
class_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [32]:
# You may find it helpful to look at CLASSIFICATION value counts >1
#  YOUR CODE GOES HERE
class_counts[class_counts > 1]

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [33]:
class_counts[class_counts > 10]

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
Name: CLASSIFICATION, dtype: int64

In [34]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
#  YOUR CODE GOES HERE
classifications_to_replace = list(class_counts[class_counts < 1000].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [35]:
# Convert categorical data to numeric with `pd.get_dummies`
#  YOUR CODE GOES HERE
application_with_dummies_df = pd.get_dummies(application_df)
application_with_dummies_df

,STATUS,ASK_AMT,IS_SUCCESSFUL,NAME_AACE INTERNATIONAL,NAME_ACE MENTOR PROGRAM OF AMERICA INC,NAME_AFRICAN-AMERICAN POSTAL LEAGUE UNITED FOR SUCCESS A-PLUS,NAME_AIR FORCE ASSOCIATION,NAME_ALABAMA FEDERATION OF WOMENS CLUBS,NAME_ALABAMA TREASURE FOREST ASSOCIATION,NAME_ALBANY STATE UNIVERSITY NATIONAL ALUMNI ASSOCIATION,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34295,1,5000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34296,1,5000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34297,1,5000,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34298,1,36500179,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0

In [36]:
# Split our preprocessed data into our features and target arrays
#  YOUR CODE GOES HERE
X = application_with_dummies_df.drop(["IS_SUCCESSFUL"], axis="columns").values
y = application_with_dummies_df["IS_SUCCESSFUL"].values

# Split the preprocessed data into a training and testing dataset
#  YOUR CODE GOES HERE
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [37]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [38]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#  YOUR CODE GOES HERE
number_input_feature = len(X_train[0])
hidden_nodes_layers1 = 100
hidden_nodes_layers2 = 30
hidden_nodes_layers3 = 10
nn = tf.keras.models.Sequential()

# First hidden layer
#  YOUR CODE GOES HERE
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layers1, input_dim=number_input_feature, activation="relu")
)

# Second hidden layer
#  YOUR CODE GOES HERE
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layers2, activation="sigmoid")
)

nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layers3, activation="sigmoid")
)


# Output layer
#  YOUR CODE GOES HERE
nn.add(
    tf.keras.layers.Dense(units=1, activation="sigmoid")
)

# Check the structure of the model
nn.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_8 (Dense)             (None, 100)               39900

 dense_9 (Dense)             (None, 30)                3030

 dense_10 (Dense)            (None, 10)                310

 dense_11 (Dense)            (None, 1)                 11

=================================================================
Total params: 43251 (168.95 KB)
Trainable params: 43251 (168.95 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [39]:
# Compile the model
#  YOUR CODE GOES HERE
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [40]:
# Train the model
#  YOUR CODE GOES HERE
fit_model = nn.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 [==============================] - 5s 4ms/step - loss: 0.5037 - accuracy: 0.7693
Epoch 2/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4438 - accuracy: 0.7955
Epoch 3/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4350 - accuracy: 0.7972
Epoch 4/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4303 - accuracy: 0.7969
Epoch 5/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4276 - accuracy: 0.7977
Epoch 6/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4259 - accuracy: 0.7981
Epoch 7/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4238 - accuracy: 0.7982
Epoch 8/100
804/804 [==============================] - 4s 4ms/step - loss: 0.4229 - accuracy: 0.7986
Epoch 9/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4213 - accuracy: 0.7997
Epoch 10/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4209 - accuracy: 0.7995
Epoch 11/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4193 - accuracy: 0.8005
Epoch 12/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4187 - accuracy: 0.8006
Epoch 13/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4182 - accuracy: 0.8013
Epoch 14/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4172 - accuracy: 0.8017
Epoch 15/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4168 - accuracy: 0.8016
Epoch 16/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4160 - accuracy: 0.8020
Epoch 17/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4154 - accuracy: 0.8021
Epoch 18/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4151 - accuracy: 0.8022
Epoch 19/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4141 - accuracy: 0.8029
Epoch 20/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4137 - accuracy: 0.8033
Epoch 21/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4133 - accuracy: 0.8038
Epoch 22/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4128 - accuracy: 0.8038
Epoch 23/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4121 - accuracy: 0.8036
Epoch 24/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4120 - accuracy: 0.8048
Epoch 25/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4115 - accuracy: 0.8029
Epoch 26/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4114 - accuracy: 0.8043
Epoch 27/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4111 - accuracy: 0.8039
Epoch 28/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4106 - accuracy: 0.8050
Epoch 29/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4103 - accuracy: 0.8047
Epoch 30/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4100 - accuracy: 0.8048
Epoch 31/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4096 - accuracy: 0.8040
Epoch 32/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4090 - accuracy: 0.8059
Epoch 33/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4084 - accuracy: 0.8054
Epoch 34/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4087 - accuracy: 0.8055
Epoch 35/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4084 - accuracy: 0.8047
Epoch 36/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4079 - accuracy: 0.8065
Epoch 37/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4074 - accuracy: 0.8049
Epoch 38/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4075 - accuracy: 0.8065
Epoch 39/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4075 - accuracy: 0.8058
Epoch 40/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4067 - accuracy: 0.8057
Epoch 41/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4065 - accuracy: 0.8071
Epoch 42/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4063 - accuracy: 0.8063
Epoch 43/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4057 - accuracy: 0.8062
Epoch 44/100
804/804 [==============================] - 4s 4ms/step - loss: 0.4054 - accuracy: 0.8061
Epoch 45/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4054 - accuracy: 0.8067
Epoch 46/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4053 - accuracy: 0.8064
Epoch 47/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4048 - accuracy: 0.8066
Epoch 48/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4049 - accuracy: 0.8066
Epoch 49/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4048 - accuracy: 0.8067
Epoch 50/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4049 - accuracy: 0.8071
Epoch 51/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4042 - accuracy: 0.8068
Epoch 52/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4042 - accuracy: 0.8073
Epoch 53/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4043 - accuracy: 0.8077
Epoch 54/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4039 - accuracy: 0.8065
Epoch 55/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4037 - accuracy: 0.8072
Epoch 56/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4036 - accuracy: 0.8082
Epoch 57/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4034 - accuracy: 0.8082
Epoch 58/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4034 - accuracy: 0.8077
Epoch 59/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4038 - accuracy: 0.8069
Epoch 60/100
804/804 [==============================] - 4s 4ms/step - loss: 0.4028 - accuracy: 0.8077
Epoch 61/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4027 - accuracy: 0.8079
Epoch 62/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4029 - accuracy: 0.8084
Epoch 63/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4030 - accuracy: 0.8074
Epoch 64/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4026 - accuracy: 0.8078
Epoch 65/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4031 - accuracy: 0.8076
Epoch 66/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4026 - accuracy: 0.8083
Epoch 67/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4021 - accuracy: 0.8079
Epoch 68/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4027 - accuracy: 0.8076
Epoch 69/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4016 - accuracy: 0.8070
Epoch 70/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4016 - accuracy: 0.8078
Epoch 71/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4017 - accuracy: 0.8080
Epoch 72/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4024 - accuracy: 0.8085
Epoch 73/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4022 - accuracy: 0.8085
Epoch 74/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4019 - accuracy: 0.8080
Epoch 75/100
804/804 [==============================] - 5s 6ms/step - loss: 0.4013 - accuracy: 0.8092
Epoch 76/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4016 - accuracy: 0.8087
Epoch 77/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4016 - accuracy: 0.8079
Epoch 78/100
804/804 [==============================] - 5s 6ms/step - loss: 0.4015 - accuracy: 0.8090
Epoch 79/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4017 - accuracy: 0.8080
Epoch 80/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4017 - accuracy: 0.8080
Epoch 81/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4021 - accuracy: 0.8085
Epoch 82/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4017 - accuracy: 0.8082
Epoch 83/100
804/804 [==============================] - 5s 6ms/step - loss: 0.4015 - accuracy: 0.8086
Epoch 84/100
804/804 [==============================] - 5s 6ms/step - loss: 0.4017 - accuracy: 0.8086
Epoch 85/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4016 - accuracy: 0.8089
Epoch 86/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4019 - accuracy: 0.8077
Epoch 87/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4013 - accuracy: 0.8085
Epoch 88/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4011 - accuracy: 0.8083
Epoch 89/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4020 - accuracy: 0.8090
Epoch 90/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4022 - accuracy: 0.8090
Epoch 91/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4018 - accuracy: 0.8086
Epoch 92/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4020 - accuracy: 0.8082
Epoch 93/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4017 - accuracy: 0.8089
Epoch 94/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4015 - accuracy: 0.8087
Epoch 95/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4018 - accuracy: 0.8085
Epoch 96/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4018 - accuracy: 0.8085
Epoch 97/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4017 - accuracy: 0.8089
Epoch 98/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4015 - accuracy: 0.8089
Epoch 99/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4017 - accuracy: 0.8086
Epoch 100/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4022 - accuracy: 0.8097

In [41]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.4518 - accuracy: 0.7886 - 605ms/epoch - 2ms/step
Loss: 0.4517751932144165, Accuracy: 0.7885714173316956

In [42]:
# Export our model to HDF5 file
#  YOUR CODE GOES HERE
nn.save("AlphabetSoupCharity_Optimization.h5")

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

# The report should contain the following:

# Overview of the analysis: Explain the purpose of this analysis.

# Results: Using bulleted lists and images to support your answers, address the following questions:

#Data Preprocessing

1. What variable(s) are the target(s) for your model?

The Target is the "Is-Successful" column

2. What variable(s) are the features for your model?

NAME, APPLICATION_TYPE, AFFILIATION, CLASSIFICATION,	USE_CASE,	ORGANIZATION,	STATUS,	INCOME_AMT,	SPECIAL_CONSIDERATIONS,	ASK_AMT.

3. What variable(s) should be removed from the input data because they are neither targets nor features?

EIN

#Compiling, Training, and Evaluating the Model

1. How many neurons, layers, and activation functions did you select for your neural network model, and why?


Employing three hidden layers with a multitude of neurons is motivated by the observed increase in accuracy beyond 75%, albeit at a significant computational cost. The initial activation function is relu, while subsequent layers utilize sigmoid, a choice anticipated to potentially enhance accuracy. Additionally, fine-tuning the data through techniques like one-hot encoding, specifically using 'get_dummies', may factor into achieving improved accuracy scores.

2. Were you able to achieve the target model performance?

Yes we were able to increase the accuracy.

3. What steps did you take in your attempts to increase model performance?

To enhance efficiency, it is necessary to convert the "NAME" attribute into data points with a significant impact. However, this process comes with a cost, as it involves adding a third layer with a sigmoid activation function. This strategic adjustment is expected to yield improvements in efficiency, albeit at an increased computational expense.

#Summary: Summarize the overall results of the deep learning model.

Overall, achieving an accuracy rate above 75% indicates successful classification in the test dataset 75% of the time. Specifically, an applicant stands an 80% chance of success if they adhere to the following criteria: the applicant's name appears more than 5 times, and the type of applications falls within the categories T3, T4, T5, T6, T7, T8, T10, and T19. These conditions contribute to a higher likelihood of successful classification based on the given format.

#Include a recommendation for how a different model could solve this classification problem, and then explain your recommendation.


Utilizing either a RandomForest model or a decision model is a viable approach to test accuracy. Employing multiple models enhances our understanding of how well each fits the data and whether there's a risk of overfitting. By exploring various models, we can identify the one that best suits our dataset, balancing the need for high accuracy without overfitting to ensure robust performance.